Update make_canadian

diff --git a/scripts/make_canadian b/scripts/make_canadian
--- a/scripts/make_canadian
+++ b/scripts/make_canadian
@@ -92,21 +92,6 @@ function install_packages()
 }
 
 
-function get_host_toolchain_type()
-{
-	local HOST="$1"
-
-	local build_type
-	build_type="$(get_build_machine_type)"
-	if [[ $build_type == "linux-x64" && $HOST == "x86_64-unknown-linux-gnu" ]]; then
-			# Host=generic x86-64, build=x86-64 level > 1 (currently 3).
-			build_type="linux-x64v3"
-	fi
-
-	printf '%s\n' "$build_type"
-}
-
-
 function get_host_toolchain()
 {
 	local HOST="$1"
@@ -120,24 +105,51 @@ function get_host_toolchain()
 			return 1
 			;;
 	esac
-	build_type="$(get_host_toolchain_type "$HOST")"
-	local arch="${build_type##*-}"
-	local name="${build_type}_${HOST}.tar.xz"
-	if [ ! -f "$name" ]; then
-		local url=""
-		case $HOST in
-			*-gnu)
-				url="${CROSS_GNU_URL}/gnu-cross/releases/download/${arch}-${CROSS_GNU_VER}/${name}"
-				;;
-			*-mingw32)
-				url="${CROSS_MINGW_URL}/mingw-cross/releases/download/${arch}-${CROSS_MINGW_VER}/${name}"
-				;;
-		esac
-		if ! wget -nv -nc -T 120 --tries=20 "$url"; then
-			echo "[ERROR] Host not supported (${HOST})." >&2
-			return 1
+
+	local build_types="$build"
+	if [[ $build == "linux-x64" && $HOST == "x86_64-unknown-linux-gnu" ]]; then
+		# Host=generic x86-64, build=x86-64 level > 1.
+		local gcc_arch
+		gcc_arch=$(gcc -Q --help=target | grep "^[[:space:]]*-march" | awk '{print $2}')
+		if [[ $gcc_arch =~ ^x86-64-v([1-9][0-9]*)$ ]]; then
+			build_types="linux-x64v${BASH_REMATCH[1]} ${build}"
 		fi
 	fi
+
+	local host_toolchain_name=""
+	for build_type in $build_types; do
+		local name="${build_type}_${HOST}.tar.xz"
+		if [ -f "$name" ]; then
+			host_toolchain_name=$name
+			break
+		fi
+	done
+	if [ -z "$host_toolchain_name" ]; then
+		for build_type in $build_types; do
+			local arch="${build_type##*-}"
+			local name="${build_type}_${HOST}.tar.xz"
+			local url=""
+			case $HOST in
+				*-gnu)
+					url="${CROSS_GNU_URL}/gnu-cross/releases/download/${arch}-${CROSS_GNU_VER}/${name}"
+					;;
+				*-mingw32)
+					url="${CROSS_MINGW_URL}/mingw-cross/releases/download/${arch}-${CROSS_MINGW_VER}/${name}"
+					;;
+			esac
+			if ! wget -nv -nc -T 120 --tries=20 "$url"; then
+				continue
+			fi
+			host_toolchain_name=$name
+			break
+		done
+	fi
+	if [ -z "$host_toolchain_name" ]; then
+		echo "[ERROR] Host not supported (${HOST})." >&2
+		return 1
+	fi
+
+	printf '%s\n' "$host_toolchain_name"
 }
 
 
@@ -145,6 +157,7 @@ function build_target()
 {
 	local HOST="$1"
 	local TARGET="$2"
+	local HOST_TOOLCHAIN_NAME="$3"
 
 	local src_dir="$CTNG_SOURCE_DIR"
 	if [ -z "$src_dir" ]; then
@@ -190,9 +203,7 @@ function build_target()
 	echo -e "\n******\n"
 
 	# Install the host toolchain
-	local build_type
-	build_type="$(get_host_toolchain_type "$HOST")"
-	tar -xf "../${build_type}_${HOST}.tar.xz"
+	tar -xf "../${HOST_TOOLCHAIN_NAME}"
 
 	(
 		export PATH="$(pwd)/${HOST}/bin:$PATH"
@@ -293,8 +304,10 @@ fi
 
 install_packages
 
+host_toolchain_name=""
+
 if [ "$TARGET" != "crosstool-ng" ]; then
-	get_host_toolchain "$HOST"
+	host_toolchain_name=$(get_host_toolchain "$HOST")
 fi
 
 if [ ! -f "crosstool-ng.tar.xz" ]; then
@@ -302,7 +315,7 @@ if [ ! -f "crosstool-ng.tar.xz" ]; then
 fi
 
 if [ "$TARGET" != "crosstool-ng" ]; then
-	build_target "$HOST" "$TARGET"
+	build_target "$HOST" "$TARGET" "$host_toolchain_name"
 fi
 
 echo -e "\nDone.\n"
